# Generated by Django 4.2.1 on 2023-06-06 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_caring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caring',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='caring',
            name='care',
            field=models.CharField(choices=[('W', 'Water'), ('F', 'Fertilizer'), ('M', 'Mist')], default='W', max_length=1, verbose_name='Care Given'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.plant')),
            ],
        ),
    ]
